name: featureimpact
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        run: |
          git fetch --depth=500
          git fetch --tags
          python3 setup.py sdist
          pip3 install dist/*.gz
          pip3 install sklearn nose2
          nose2 -v test
