name: featureimpact
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        run: |
          git fetch --depth=500
          git fetch --tags
          python3 -m venv venv
          source venv/bin/activate
          pip3 install -e .
          pip3 install sklearn nose2
          python3 setup.py install
          nose2 -v test
