name: featureimpact
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: run tests
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          python3 setup.py sdist
          pip3 install dist/*.gz
          pip3 install sklearn nose2
          nose2 -v test
